volumes:
  mach-moto-postgres18-3:

services:
  mach-moto-server:
    container_name: mach-moto-server
    build: .
    ports:
      - "127.0.0.1:3333:3333"
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - PORT=3333
      - NODE_ENV=production
      # This URL tells the Node app how to talk to the 'db' container
      - DATABASE_URL=postgresql://motouser:${POSTGRES_PWD}@db:5432/motodb

  db:
    image: postgres:18.3-alpine
    container_name: mach-moto-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=motouser
      - POSTGRES_PASSWORD=${POSTGRES_PWD} # Change this in production!
      - POSTGRES_DB=motodb
    volumes:
      - mach-moto-postgres18-3:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
